<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../src/L2.Studio.Configurations/L2.Studio.Configurations.csproj" />
    <ProjectReference Include="../../src/L2.Studio.Context/L2.Studio.Context.csproj" />
    <ProjectReference Include="../../src/L2.Studio.Messages/L2.Studio.Messages.csproj" />
    <ProjectReference Include="../../src/L2.Studio.Repositories/L2.Studio.Repositories.csproj" />
    <ProjectReference Include="../../src/L2.Studio.Repositories.Interfaces/L2.Studio.Repositories.Interfaces.csproj" />
    <ProjectReference Include="../../src/L2.Studio.Services/L2.Studio.Services.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
