services:
  studio:
    image: ghcr.io/podvysotskyi/l2-studio:${L2_STUDIO_IMAGE_TAG:-latest}
    ports: ['3001:3001']
    environment:
      NUXT_PUBLIC_STUDIO_API_BASE: ${NUXT_PUBLIC_STUDIO_API_BASE:-http://localhost:5101}
