// <auto-generated />
using L2.Studio.Content;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace L2.Studio.Content.Migrations
{
    [DbContext(typeof(GameContentDbContext))]
    [Migration("20260805030000_RemoveNoneRaceAndMakeNpcRaceNullable")]
    partial class RemoveNoneRaceAndMakeNpcRaceNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("L2.Studio.Content.Entities.Npc", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("NpcRaceId")
                        .HasColumnType("integer")
                        .HasColumnName("npc_race_id");

                    b.Property<int>("NpcSexId")
                        .HasColumnType("integer")
                        .HasColumnName("npc_sex_id");

                    b.Property<int>("NpcTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("npc_type_id");

                    b.HasKey("Id");

                    b.HasIndex("NpcRaceId")
                        .HasDatabaseName("ix_npcs_npc_race_id");

                    b.HasIndex("NpcSexId")
                        .HasDatabaseName("ix_npcs_npc_sex_id");

                    b.HasIndex("NpcTypeId")
                        .HasDatabaseName("ix_npcs_npc_type_id");

                    b.ToTable("npcs", "content", t =>
                        {
                            t.HasCheckConstraint("ck_npcs_level", "level BETWEEN 1 AND 255");
                        });
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.NpcRace", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_npc_races_name");

                    b.ToTable("npc_races", "content");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.NpcSex", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_npc_sexes_name");

                    b.ToTable("npc_sexes", "content");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.NpcType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_npc_types_name");

                    b.ToTable("npc_types", "content");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.Npc", b =>
                {
                    b.HasOne("L2.Studio.Content.Entities.NpcRace", "NpcRace")
                        .WithMany("Npcs")
                        .HasForeignKey("NpcRaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("L2.Studio.Content.Entities.NpcSex", "NpcSex")
                        .WithMany("Npcs")
                        .HasForeignKey("NpcSexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Content.Entities.NpcType", "NpcType")
                        .WithMany("Npcs")
                        .HasForeignKey("NpcTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NpcRace");

                    b.Navigation("NpcSex");

                    b.Navigation("NpcType");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.NpcRace", b =>
                {
                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.NpcSex", b =>
                {
                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.NpcType", b =>
                {
                    b.Navigation("Npcs");
                });
#pragma warning restore 612, 618
        }
    }
}
