// <auto-generated />
using System;
using L2.Studio.Content;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace L2.Studio.Content.Migrations
{
    [DbContext(typeof(GameContentDbContext))]
    [Migration("20260809023341_AddAssetCatalogs")]
    partial class AddAssetCatalogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("L2.Studio.Content.Entities.AssetCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<int?>("Protocol")
                        .HasColumnType("integer")
                        .HasColumnName("protocol");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("SourceFolder")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_folder");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_hash");

                    b.HasKey("Id");

                    b.HasIndex("Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_catalogs_active_kind")
                        .HasFilter("is_active");

                    b.ToTable("asset_catalogs", "content");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.AssetCatalogGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_catalog_groups_catalog_name");

                    b.ToTable("asset_catalog_groups", "content");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.AssetCatalogItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<string>("GroupName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("group_name");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "Name")
                        .HasDatabaseName("ix_asset_catalog_items_catalog_name");

                    b.HasIndex("CatalogId", "Status")
                        .HasDatabaseName("ix_asset_catalog_items_catalog_status");

                    b.HasIndex("CatalogId", "GroupName", "Name")
                        .HasDatabaseName("ix_asset_catalog_items_catalog_group_name");

                    b.ToTable("asset_catalog_items", "content");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.AssetImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("integer")
                        .HasColumnName("processed_count");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer")
                        .HasColumnName("skipped_count");

                    b.Property<string>("SourceHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_hash");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("source_path");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_count");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("warnings_json");

                    b.HasKey("Id");

                    b.HasIndex("Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_import_jobs_active_kind")
                        .HasFilter("\"status\" IN ('queued', 'running')");

                    b.HasIndex("Kind", "Status", "RequestedAt")
                        .HasDatabaseName("ix_asset_import_jobs_claim");

                    b.ToTable("asset_import_jobs", "content");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.Npc", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("NpcRaceId")
                        .HasColumnType("integer")
                        .HasColumnName("npc_race_id");

                    b.Property<int>("NpcSexId")
                        .HasColumnType("integer")
                        .HasColumnName("npc_sex_id");

                    b.Property<int>("NpcTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("npc_type_id");

                    b.HasKey("Id");

                    b.HasIndex("NpcRaceId")
                        .HasDatabaseName("ix_npcs_npc_race_id");

                    b.HasIndex("NpcSexId")
                        .HasDatabaseName("ix_npcs_npc_sex_id");

                    b.HasIndex("NpcTypeId")
                        .HasDatabaseName("ix_npcs_npc_type_id");

                    b.ToTable("npcs", "content", t =>
                        {
                            t.HasCheckConstraint("ck_npcs_level", "level BETWEEN 1 AND 255");
                        });
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.NpcRace", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_npc_races_name");

                    b.ToTable("npc_races", "content");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.NpcSex", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_npc_sexes_name");

                    b.ToTable("npc_sexes", "content");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.NpcType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_npc_types_name");

                    b.ToTable("npc_types", "content");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<short>("Levels")
                        .HasColumnType("smallint")
                        .HasColumnName("levels");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("SkillOperateTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_operate_type_id");

                    b.Property<int?>("SkillTargetTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_target_type_id");

                    b.HasKey("Id");

                    b.HasIndex("SkillOperateTypeId")
                        .HasDatabaseName("ix_skills_skill_operate_type_id");

                    b.HasIndex("SkillTargetTypeId")
                        .HasDatabaseName("ix_skills_skill_target_type_id");

                    b.ToTable("skills", "content", t =>
                        {
                            t.HasCheckConstraint("ck_skills_levels", "levels BETWEEN 1 AND 255");
                        });
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.SkillIcon", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("SkillId", "Level");

                    b.ToTable("skill_icons", "content", t =>
                        {
                            t.HasCheckConstraint("ck_skill_icons_level", "level BETWEEN 1 AND 255");
                        });
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.SkillOperateType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skill_operate_types_name");

                    b.ToTable("skill_operate_types", "content");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.SkillTargetType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skill_target_types_name");

                    b.ToTable("skill_target_types", "content");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.AssetCatalogGroup", b =>
                {
                    b.HasOne("L2.Studio.Content.Entities.AssetCatalog", "Catalog")
                        .WithMany("Groups")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.AssetCatalogItem", b =>
                {
                    b.HasOne("L2.Studio.Content.Entities.AssetCatalog", "Catalog")
                        .WithMany("Items")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.Npc", b =>
                {
                    b.HasOne("L2.Studio.Content.Entities.NpcRace", "NpcRace")
                        .WithMany("Npcs")
                        .HasForeignKey("NpcRaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("L2.Studio.Content.Entities.NpcSex", "NpcSex")
                        .WithMany("Npcs")
                        .HasForeignKey("NpcSexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Content.Entities.NpcType", "NpcType")
                        .WithMany("Npcs")
                        .HasForeignKey("NpcTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NpcRace");

                    b.Navigation("NpcSex");

                    b.Navigation("NpcType");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.Skill", b =>
                {
                    b.HasOne("L2.Studio.Content.Entities.SkillOperateType", "SkillOperateType")
                        .WithMany("Skills")
                        .HasForeignKey("SkillOperateTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("L2.Studio.Content.Entities.SkillTargetType", "SkillTargetType")
                        .WithMany("Skills")
                        .HasForeignKey("SkillTargetTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SkillOperateType");

                    b.Navigation("SkillTargetType");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.SkillIcon", b =>
                {
                    b.HasOne("L2.Studio.Content.Entities.Skill", "Skill")
                        .WithMany("SkillIcons")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.AssetCatalog", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.NpcRace", b =>
                {
                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.NpcSex", b =>
                {
                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.NpcType", b =>
                {
                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.Skill", b =>
                {
                    b.Navigation("SkillIcons");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.SkillOperateType", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("L2.Studio.Content.Entities.SkillTargetType", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
