// <auto-generated />
// Source: L2J_Mobius_CT_0_Interlude game/data/stats/players/classList.xml.
using L2.Studio.Content.Identifiers;

namespace L2.Studio.Content.Seeding;

public static class PlayerClassSeedValues
{
    private static PlayerClassSeedDefinition Mage(
        PlayerClassId id,
        string name,
        PlayerClassId? parentClassId) => new(id, name, parentClassId, true);

    private static IReadOnlyList<PlayerSexId> BothSexes { get; } =
        [PlayerSexId.Male, PlayerSexId.Female];

    private static IReadOnlyDictionary<PlayerRaceId, IReadOnlyList<PlayerClassRaceSeedDefinition>>
        CanonicalRaces { get; } = Enum.GetValues<PlayerRaceId>().ToDictionary(
            raceId => raceId,
            raceId => (IReadOnlyList<PlayerClassRaceSeedDefinition>)
                [new PlayerClassRaceSeedDefinition(raceId, BothSexes)]);

    public static IReadOnlyList<PlayerClassRaceSeedDefinition> ForCanonicalRace(PlayerClassId classId)
    {
        var id = (int)classId;
        var raceId = id switch
        {
            >= 0 and <= 17 or >= 88 and <= 98 => PlayerRaceId.Human,
            >= 18 and <= 30 or >= 99 and <= 105 => PlayerRaceId.Elf,
            >= 31 and <= 43 or >= 106 and <= 112 => PlayerRaceId.DarkElf,
            >= 44 and <= 52 or >= 113 and <= 116 => PlayerRaceId.Orc,
            >= 53 and <= 57 or >= 117 and <= 118 => PlayerRaceId.Dwarf,
            _ => throw new ArgumentOutOfRangeException(nameof(classId), classId, "Unknown player class ID.")
        };
        return CanonicalRaces[raceId];
    }

    public static IReadOnlyList<PlayerClassSeedDefinition> PlayerClasses { get; } =
    [
        new(PlayerClassId.HumanFighter, "Human Fighter", null),
        new(PlayerClassId.Warrior, "Warrior", PlayerClassId.HumanFighter),
        new(PlayerClassId.Gladiator, "Gladiator", PlayerClassId.Warrior),
        new(PlayerClassId.Warlord, "Warlord", PlayerClassId.Warrior),
        new(PlayerClassId.HumanKnight, "Human Knight", PlayerClassId.HumanFighter),
        new(PlayerClassId.Paladin, "Paladin", PlayerClassId.HumanKnight),
        new(PlayerClassId.DarkAvenger, "Dark Avenger", PlayerClassId.HumanKnight),
        new(PlayerClassId.Rogue, "Rogue", PlayerClassId.HumanFighter),
        new(PlayerClassId.TreasureHunter, "Treasure Hunter", PlayerClassId.Rogue),
        new(PlayerClassId.Hawkeye, "Hawkeye", PlayerClassId.Rogue),
        Mage(PlayerClassId.HumanMystic, "Human Mystic", null),
        Mage(PlayerClassId.HumanWizard, "Human Wizard", PlayerClassId.HumanMystic),
        Mage(PlayerClassId.Sorcerer, "Sorcerer", PlayerClassId.HumanWizard),
        Mage(PlayerClassId.Necromancer, "Necromancer", PlayerClassId.HumanWizard),
        Mage(PlayerClassId.Warlock, "Warlock", PlayerClassId.HumanWizard),
        Mage(PlayerClassId.Cleric, "Cleric", PlayerClassId.HumanMystic),
        Mage(PlayerClassId.Bishop, "Bishop", PlayerClassId.Cleric),
        Mage(PlayerClassId.Prophet, "Prophet", PlayerClassId.Cleric),
        new(PlayerClassId.ElvenFighter, "Elven Fighter", null),
        new(PlayerClassId.ElvenKnight, "Elven Knight", PlayerClassId.ElvenFighter),
        new(PlayerClassId.TempleKnight, "Temple Knight", PlayerClassId.ElvenKnight),
        new(PlayerClassId.SwordSinger, "Sword Singer", PlayerClassId.ElvenKnight),
        new(PlayerClassId.ElvenScout, "Elven Scout", PlayerClassId.ElvenFighter),
        new(PlayerClassId.PlainsWalker, "Plains Walker", PlayerClassId.ElvenScout),
        new(PlayerClassId.SilverRanger, "Silver Ranger", PlayerClassId.ElvenScout),
        Mage(PlayerClassId.ElvenMystic, "Elven Mystic", null),
        Mage(PlayerClassId.ElvenWizard, "Elven Wizard", PlayerClassId.ElvenMystic),
        Mage(PlayerClassId.Spellsinger, "Spellsinger", PlayerClassId.ElvenWizard),
        Mage(PlayerClassId.ElementalSummoner, "Elemental Summoner", PlayerClassId.ElvenWizard),
        Mage(PlayerClassId.ElvenOracle, "Elven Oracle", PlayerClassId.ElvenMystic),
        Mage(PlayerClassId.ElvenElder, "Elven Elder", PlayerClassId.ElvenOracle),
        new(PlayerClassId.DarkFighter, "Dark Fighter", null),
        new(PlayerClassId.PalusKnight, "Palus Knight", PlayerClassId.DarkFighter),
        new(PlayerClassId.ShillienKnight, "Shillien Knight", PlayerClassId.PalusKnight),
        new(PlayerClassId.Bladedancer, "Bladedancer", PlayerClassId.ShillienKnight),
        new(PlayerClassId.Assassin, "Assassin", PlayerClassId.DarkFighter),
        new(PlayerClassId.AbyssWalker, "Abyss Walker", PlayerClassId.Assassin),
        new(PlayerClassId.PhantomRanger, "Phantom Ranger", PlayerClassId.Assassin),
        Mage(PlayerClassId.DarkMystic, "Dark Mystic", null),
        Mage(PlayerClassId.DarkWizard, "Dark Wizard", PlayerClassId.DarkMystic),
        Mage(PlayerClassId.Spellhowler, "Spellhowler", PlayerClassId.DarkWizard),
        Mage(PlayerClassId.PhantomSummoner, "Phantom Summoner", PlayerClassId.DarkWizard),
        Mage(PlayerClassId.ShillienOracle, "Shillien Oracle", PlayerClassId.DarkMystic),
        Mage(PlayerClassId.ShillienElder, "Shillien Elder", PlayerClassId.ShillienOracle),
        new(PlayerClassId.OrcFighter, "Orc Fighter", null),
        new(PlayerClassId.OrcRaider, "Orc Raider", PlayerClassId.OrcFighter),
        new(PlayerClassId.Destroyer, "Destroyer", PlayerClassId.OrcRaider),
        new(PlayerClassId.Monk, "Monk", PlayerClassId.OrcFighter),
        new(PlayerClassId.Tyrant, "Tyrant", PlayerClassId.Monk),
        Mage(PlayerClassId.OrcMystic, "Orc Mystic", null),
        Mage(PlayerClassId.OrcShaman, "Orc Shaman", PlayerClassId.OrcMystic),
        Mage(PlayerClassId.Overlord, "Overlord", PlayerClassId.OrcShaman),
        Mage(PlayerClassId.Warcryer, "Warcryer", PlayerClassId.OrcShaman),
        new(PlayerClassId.DwarfFighter, "Dwarf Fighter", null),
        new(PlayerClassId.Scavenger, "Scavenger", PlayerClassId.DwarfFighter),
        new(PlayerClassId.BountyHunter, "Bounty Hunter", PlayerClassId.Scavenger),
        new(PlayerClassId.Artisan, "Artisan", PlayerClassId.DwarfFighter),
        new(PlayerClassId.Warsmith, "Warsmith", PlayerClassId.Artisan),
        new(PlayerClassId.Duelist, "Duelist", PlayerClassId.Gladiator),
        new(PlayerClassId.Dreadnought, "Dreadnought", PlayerClassId.Warlord),
        new(PlayerClassId.PhoenixKnight, "Phoenix Knight", PlayerClassId.Paladin),
        new(PlayerClassId.HellKnight, "Hell Knight", PlayerClassId.DarkAvenger),
        new(PlayerClassId.Sagittarius, "Sagittarius", PlayerClassId.Hawkeye),
        new(PlayerClassId.Adventurer, "Adventurer", PlayerClassId.TreasureHunter),
        Mage(PlayerClassId.Archmage, "Archmage", PlayerClassId.Sorcerer),
        Mage(PlayerClassId.Soultaker, "Soultaker", PlayerClassId.Necromancer),
        Mage(PlayerClassId.ArcanaLord, "Arcana Lord", PlayerClassId.Warlock),
        Mage(PlayerClassId.Cardinal, "Cardinal", PlayerClassId.Bishop),
        Mage(PlayerClassId.Hierophant, "Hierophant", PlayerClassId.Prophet),
        new(PlayerClassId.EvasTemplar, "Eva's Templar", PlayerClassId.TempleKnight),
        new(PlayerClassId.SwordMuse, "Sword Muse", PlayerClassId.SwordSinger),
        new(PlayerClassId.WindRider, "Wind Rider", PlayerClassId.PlainsWalker),
        new(PlayerClassId.MoonlightSentinel, "Moonlight Sentinel", PlayerClassId.SilverRanger),
        Mage(PlayerClassId.MysticMuse, "Mystic Muse", PlayerClassId.Spellsinger),
        Mage(PlayerClassId.ElementalMaster, "Elemental Master", PlayerClassId.ElvenWizard),
        Mage(PlayerClassId.EvasSaint, "Eva's Saint", PlayerClassId.ElvenElder),
        new(PlayerClassId.ShillienTemplar, "Shillien Templar", PlayerClassId.ShillienKnight),
        new(PlayerClassId.SpectralDancer, "Spectral Dancer", PlayerClassId.Bladedancer),
        new(PlayerClassId.GhostHunter, "Ghost Hunter", PlayerClassId.AbyssWalker),
        new(PlayerClassId.GhostSentinel, "Ghost Sentinel", PlayerClassId.PhantomRanger),
        Mage(PlayerClassId.StormScreamer, "Storm Screamer", PlayerClassId.Spellhowler),
        Mage(PlayerClassId.SpectralMaster, "Spectral Master", PlayerClassId.PhantomSummoner),
        Mage(PlayerClassId.ShillienSaint, "Shillien Saint", PlayerClassId.ShillienElder),
        new(PlayerClassId.Titan, "Titan", PlayerClassId.Destroyer),
        new(PlayerClassId.GrandKhavatari, "Grand Khavatari", PlayerClassId.Tyrant),
        Mage(PlayerClassId.Dominator, "Dominator", PlayerClassId.Overlord),
        Mage(PlayerClassId.DoomCryer, "Doom Cryer", PlayerClassId.Warcryer),
        new(PlayerClassId.FortuneSeeker, "Fortune Seeker", PlayerClassId.BountyHunter),
        new(PlayerClassId.Maestro, "Maestro", PlayerClassId.Warsmith)
    ];
}
