namespace L2.Tools.StaticMeshConverter;

public sealed record StaticMeshMaterialBinding(
    string Name,
    string? DiffuseUrl,
    string? OpacityUrl,
    string? EmissiveUrl,
    StaticMeshBlendMode BlendMode,
    bool DoubleSided,
    float AlphaCutoff,
    bool DepthWrite,
    bool DepthTest,
    StaticMeshOpacitySource OpacitySource = StaticMeshOpacitySource.None,
    StaticMeshOpacityChannel OpacityChannel = StaticMeshOpacityChannel.Alpha,
    float PanRate = 0,
    float PanRateV = 0,
    float RotationRate = 0,
    string? DetailUrl = null,
    float DetailScale = 8,
    StaticMeshTextureAnimation? DiffuseAnimation = null,
    StaticMeshTextureAnimation? OpacityAnimation = null,
    StaticMeshTextureAnimation? EmissiveAnimation = null,
    StaticMeshWindMode WindMode = StaticMeshWindMode.None,
    StaticMeshMaterialTint? Tint = null,
    StaticMeshUvOscillation? UvOscillation = null,
    bool Unlit = false,
    StaticMeshMaterialFade? Fade = null,
    StaticMeshMaterialComposite? Composite = null,
    string? SelfIlluminationMaskUrl = null,
    string? SpecularUrl = null,
    string? SpecularityMaskUrl = null,
    bool PerformLightingOnSpecularPass = false);
