using L2.Studio.Context.Identifiers;

namespace L2.Studio.Worker;

public sealed partial class C1PlayerCatalog
{
    private static readonly PlayerClassDefinition[] ClassDefinitions =
    [
        new((PlayerClassId)0, PlayerRaceId.Human, false, null, "Human Fighter"),
        new((PlayerClassId)1, PlayerRaceId.Human, false, (PlayerClassId)0, "Warrior"),
        new((PlayerClassId)2, PlayerRaceId.Human, false, (PlayerClassId)1, "Gladiator"),
        new((PlayerClassId)3, PlayerRaceId.Human, false, (PlayerClassId)1, "Warlord"),
        new((PlayerClassId)4, PlayerRaceId.Human, false, (PlayerClassId)0, "Human Knight"),
        new((PlayerClassId)5, PlayerRaceId.Human, false, (PlayerClassId)4, "Paladin"),
        new((PlayerClassId)6, PlayerRaceId.Human, false, (PlayerClassId)4, "Dark Avenger"),
        new((PlayerClassId)7, PlayerRaceId.Human, false, (PlayerClassId)0, "Rogue"),
        new((PlayerClassId)8, PlayerRaceId.Human, false, (PlayerClassId)7, "Treasure Hunter"),
        new((PlayerClassId)9, PlayerRaceId.Human, false, (PlayerClassId)7, "Hawkeye"),
        new((PlayerClassId)10, PlayerRaceId.Human, true, null, "Human Mystic"),
        new((PlayerClassId)11, PlayerRaceId.Human, true, (PlayerClassId)10, "Human Wizard"),
        new((PlayerClassId)12, PlayerRaceId.Human, true, (PlayerClassId)11, "Sorcerer"),
        new((PlayerClassId)13, PlayerRaceId.Human, true, (PlayerClassId)11, "Necromancer"),
        new((PlayerClassId)14, PlayerRaceId.Human, true, (PlayerClassId)11, "Warlock"),
        new((PlayerClassId)15, PlayerRaceId.Human, true, (PlayerClassId)10, "Cleric"),
        new((PlayerClassId)16, PlayerRaceId.Human, true, (PlayerClassId)15, "Bishop"),
        new((PlayerClassId)17, PlayerRaceId.Human, true, (PlayerClassId)15, "Prophet"),
        new((PlayerClassId)18, PlayerRaceId.Elf, false, null, "Elven Fighter"),
        new((PlayerClassId)19, PlayerRaceId.Elf, false, (PlayerClassId)18, "Elven Knight"),
        new((PlayerClassId)20, PlayerRaceId.Elf, false, (PlayerClassId)19, "Temple Knight"),
        new((PlayerClassId)21, PlayerRaceId.Elf, false, (PlayerClassId)19, "Sword Singer"),
        new((PlayerClassId)22, PlayerRaceId.Elf, false, (PlayerClassId)18, "Elven Scout"),
        new((PlayerClassId)23, PlayerRaceId.Elf, false, (PlayerClassId)22, "Plains Walker"),
        new((PlayerClassId)24, PlayerRaceId.Elf, false, (PlayerClassId)22, "Silver Ranger"),
        new((PlayerClassId)25, PlayerRaceId.Elf, true, null, "Elven Mystic"),
        new((PlayerClassId)26, PlayerRaceId.Elf, true, (PlayerClassId)25, "Elven Wizard"),
        new((PlayerClassId)27, PlayerRaceId.Elf, true, (PlayerClassId)26, "Spellsinger"),
        new((PlayerClassId)28, PlayerRaceId.Elf, true, (PlayerClassId)26, "Elemental Summoner"),
        new((PlayerClassId)29, PlayerRaceId.Elf, true, (PlayerClassId)25, "Elven Oracle"),
        new((PlayerClassId)30, PlayerRaceId.Elf, true, (PlayerClassId)29, "Elven Elder"),
        new((PlayerClassId)31, PlayerRaceId.DarkElf, false, null, "Dark Fighter"),
        new((PlayerClassId)32, PlayerRaceId.DarkElf, false, (PlayerClassId)31, "Palus Knight"),
        new((PlayerClassId)33, PlayerRaceId.DarkElf, false, (PlayerClassId)32, "Shillien Knight"),
        new((PlayerClassId)34, PlayerRaceId.DarkElf, false, (PlayerClassId)33, "Bladedancer"),
        new((PlayerClassId)35, PlayerRaceId.DarkElf, false, (PlayerClassId)31, "Assassin"),
        new((PlayerClassId)36, PlayerRaceId.DarkElf, false, (PlayerClassId)35, "Abyss Walker"),
        new((PlayerClassId)37, PlayerRaceId.DarkElf, false, (PlayerClassId)35, "Phantom Ranger"),
        new((PlayerClassId)38, PlayerRaceId.DarkElf, true, null, "Dark Mystic"),
        new((PlayerClassId)39, PlayerRaceId.DarkElf, true, (PlayerClassId)38, "Dark Wizard"),
        new((PlayerClassId)40, PlayerRaceId.DarkElf, true, (PlayerClassId)39, "Spellhowler"),
        new((PlayerClassId)41, PlayerRaceId.DarkElf, true, (PlayerClassId)39, "Phantom Summoner"),
        new((PlayerClassId)42, PlayerRaceId.DarkElf, true, (PlayerClassId)38, "Shillien Oracle"),
        new((PlayerClassId)43, PlayerRaceId.DarkElf, true, (PlayerClassId)42, "Shillien Elder"),
        new((PlayerClassId)44, PlayerRaceId.Orc, false, null, "Orc Fighter"),
        new((PlayerClassId)45, PlayerRaceId.Orc, false, (PlayerClassId)44, "Orc Raider"),
        new((PlayerClassId)46, PlayerRaceId.Orc, false, (PlayerClassId)45, "Destroyer"),
        new((PlayerClassId)47, PlayerRaceId.Orc, false, (PlayerClassId)44, "Monk"),
        new((PlayerClassId)48, PlayerRaceId.Orc, false, (PlayerClassId)47, "Tyrant"),
        new((PlayerClassId)49, PlayerRaceId.Orc, true, null, "Orc Mystic"),
        new((PlayerClassId)50, PlayerRaceId.Orc, true, (PlayerClassId)49, "Orc Shaman"),
        new((PlayerClassId)51, PlayerRaceId.Orc, true, (PlayerClassId)50, "Overlord"),
        new((PlayerClassId)52, PlayerRaceId.Orc, true, (PlayerClassId)50, "Warcryer"),
        new((PlayerClassId)53, PlayerRaceId.Dwarf, false, null, "Dwarf Fighter"),
        new((PlayerClassId)54, PlayerRaceId.Dwarf, false, (PlayerClassId)53, "Scavenger"),
        new((PlayerClassId)55, PlayerRaceId.Dwarf, false, (PlayerClassId)54, "Bounty Hunter"),
        new((PlayerClassId)56, PlayerRaceId.Dwarf, false, (PlayerClassId)53, "Artisan"),
        new((PlayerClassId)57, PlayerRaceId.Dwarf, false, (PlayerClassId)56, "Warsmith"),
        new((PlayerClassId)88, PlayerRaceId.Human, false, (PlayerClassId)2, "Duelist"),
        new((PlayerClassId)89, PlayerRaceId.Human, false, (PlayerClassId)3, "Dreadnought"),
        new((PlayerClassId)90, PlayerRaceId.Human, false, (PlayerClassId)5, "Phoenix Knight"),
        new((PlayerClassId)91, PlayerRaceId.Human, false, (PlayerClassId)6, "Hell Knight"),
        new((PlayerClassId)92, PlayerRaceId.Human, false, (PlayerClassId)9, "Sagittarius"),
        new((PlayerClassId)93, PlayerRaceId.Human, false, (PlayerClassId)8, "Adventurer"),
        new((PlayerClassId)94, PlayerRaceId.Human, true, (PlayerClassId)12, "Archmage"),
        new((PlayerClassId)95, PlayerRaceId.Human, true, (PlayerClassId)13, "Soultaker"),
        new((PlayerClassId)96, PlayerRaceId.Human, true, (PlayerClassId)14, "Arcana Lord"),
        new((PlayerClassId)97, PlayerRaceId.Human, true, (PlayerClassId)16, "Cardinal"),
        new((PlayerClassId)98, PlayerRaceId.Human, true, (PlayerClassId)17, "Hierophant"),
        new((PlayerClassId)99, PlayerRaceId.Elf, false, (PlayerClassId)20, "Eva's Templar"),
        new((PlayerClassId)100, PlayerRaceId.Elf, false, (PlayerClassId)21, "Sword Muse"),
        new((PlayerClassId)101, PlayerRaceId.Elf, false, (PlayerClassId)23, "Wind Rider"),
        new((PlayerClassId)102, PlayerRaceId.Elf, false, (PlayerClassId)24, "Moonlight Sentinel"),
        new((PlayerClassId)103, PlayerRaceId.Elf, true, (PlayerClassId)27, "Mystic Muse"),
        new((PlayerClassId)104, PlayerRaceId.Elf, true, (PlayerClassId)26, "Elemental Master"),
        new((PlayerClassId)105, PlayerRaceId.Elf, true, (PlayerClassId)30, "Eva's Saint"),
        new((PlayerClassId)106, PlayerRaceId.DarkElf, false, (PlayerClassId)33, "Shillien Templar"),
        new((PlayerClassId)107, PlayerRaceId.DarkElf, false, (PlayerClassId)34, "Spectral Dancer"),
        new((PlayerClassId)108, PlayerRaceId.DarkElf, false, (PlayerClassId)36, "Ghost Hunter"),
        new((PlayerClassId)109, PlayerRaceId.DarkElf, false, (PlayerClassId)37, "Ghost Sentinel"),
        new((PlayerClassId)110, PlayerRaceId.DarkElf, true, (PlayerClassId)40, "Storm Screamer"),
        new((PlayerClassId)111, PlayerRaceId.DarkElf, true, (PlayerClassId)41, "Spectral Master"),
        new((PlayerClassId)112, PlayerRaceId.DarkElf, true, (PlayerClassId)43, "Shillien Saint"),
        new((PlayerClassId)113, PlayerRaceId.Orc, false, (PlayerClassId)46, "Titan"),
        new((PlayerClassId)114, PlayerRaceId.Orc, false, (PlayerClassId)48, "Grand Khavatari"),
        new((PlayerClassId)115, PlayerRaceId.Orc, true, (PlayerClassId)51, "Dominator"),
        new((PlayerClassId)116, PlayerRaceId.Orc, true, (PlayerClassId)52, "Doom Cryer"),
        new((PlayerClassId)117, PlayerRaceId.Dwarf, false, (PlayerClassId)55, "Fortune Seeker"),
        new((PlayerClassId)118, PlayerRaceId.Dwarf, false, (PlayerClassId)57, "Maestro"),
    ];
}
