<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../L2.Studio.Configurations/L2.Studio.Configurations.csproj" />
    <ProjectReference Include="../L2.Studio.Contracts/L2.Studio.Contracts.csproj" />
    <ProjectReference Include="../L2.Studio.Exceptions/L2.Studio.Exceptions.csproj" />
    <ProjectReference Include="../L2.Studio.Repositories.Interfaces/L2.Studio.Repositories.Interfaces.csproj" />
  </ItemGroup>
</Project>
