namespace L2.Studio.Services;

internal sealed record TextureManifestEntry(
    string PackageName,
    string ObjectName,
    string? Url,
    int Width,
    int Height,
    string Format,
    string? Sha256,
    string Status,
    string? Error,
    string? GpuUrl = null,
    string? GpuSha256 = null,
    bool GpuCompressed = false,
    int MipCount = 0,
    TextureAnimationManifestEntry? Animation = null,
    string OriginalFolder = "",
    string Path = "",
    string SourceKey = "",
    bool Masked = false,
    bool AlphaTexture = false,
    bool HasTransparency = false,
    bool TwoSided = false,
    TextureMaterialReference? Detail = null,
    float DetailScale = 8,
    bool ClampU = false,
    bool ClampV = false);
