<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../L2.Studio.Api/L2.Studio.Api.csproj" />
    <ProjectReference Include="../L2.Studio.Content/L2.Studio.Content.csproj" />
    <ProjectReference Include="../L2.Studio.Contracts/L2.Studio.Contracts.csproj" />
    <ProjectReference Include="../L2.Studio.Worker/L2.Studio.Worker.csproj" />
    <ProjectReference Include="../../tools/L2.Tools.AudioConverter/L2.Tools.AudioConverter.csproj" />
    <ProjectReference Include="../../tools/L2.Tools.PackageReader/L2.Tools.PackageReader.csproj" />
    <ProjectReference Include="../../tools/L2.Tools.StaticMeshConverter/L2.Tools.StaticMeshConverter.csproj" />
    <ProjectReference Include="../../tools/L2.Tools.TextureConverter/L2.Tools.TextureConverter.csproj" />
  </ItemGroup>
</Project>
