// <auto-generated />
using System;
using L2.Studio.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace L2.Studio.Migrations.Migrations
{
    [DbContext(typeof(GameContentDbContext))]
    [Migration("20260811234832_AddGameVersions")]
    partial class AddGameVersions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<int?>("Protocol")
                        .HasColumnType("integer")
                        .HasColumnName("protocol");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("SourceFolder")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_folder");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_hash");

                    b.HasKey("Id");

                    b.HasIndex("GameVersion", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_catalogs_active_kind")
                        .HasFilter("is_active");

                    b.ToTable("asset_catalogs", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalogGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("CatalogId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_catalog_groups_catalog_name");

                    b.ToTable("asset_catalog_groups", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalogItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<string>("GroupName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("group_name");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("CatalogId", "Name")
                        .HasDatabaseName("ix_asset_catalog_items_catalog_name");

                    b.HasIndex("CatalogId", "Status")
                        .HasDatabaseName("ix_asset_catalog_items_catalog_status");

                    b.HasIndex("CatalogId", "GroupName", "Name")
                        .HasDatabaseName("ix_asset_catalog_items_catalog_group_name");

                    b.ToTable("asset_catalog_items", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalogSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("NormalizedSourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_source_key");

                    b.Property<string>("OutputRoot")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("output_root");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("PublishingWorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("publishing_work_item_id");

                    b.Property<string>("ReferencedOutputRootsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("referenced_output_roots_json");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_hash");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_key");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId", "NormalizedSourceKey")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_catalog_sources_catalog_source");

                    b.ToTable("asset_catalog_sources", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetImportDiagnostic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message");

                    b.Property<string>("ObjectName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_name");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_key");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage");

                    b.Property<Guid?>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey")
                        .HasDatabaseName("ix_asset_import_diagnostics_source_key");

                    b.HasIndex("WorkItemId");

                    b.HasIndex("RunId", "Severity", "Code", "Stage")
                        .HasDatabaseName("ix_asset_import_diagnostics_filters");

                    b.ToTable("asset_import_diagnostics", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CompletedFileCount")
                        .HasColumnType("integer")
                        .HasColumnName("completed_file_count");

                    b.Property<int>("DiscoveredFileCount")
                        .HasColumnType("integer")
                        .HasColumnName("discovered_file_count");

                    b.Property<DateTimeOffset?>("DiscoveryFinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovery_finished_at");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<int>("FailedFileCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_file_count");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("NormalizedRequestedSourceKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_requested_source_key");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequestedSourceKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("requested_source_key");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("SucceededFileCount")
                        .HasColumnType("integer")
                        .HasColumnName("succeeded_file_count");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trigger_type");

                    b.Property<int>("WarningFileCount")
                        .HasColumnType("integer")
                        .HasColumnName("warning_file_count");

                    b.HasKey("Id");

                    b.HasIndex("GameVersion", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_import_runs_active_full_scan_kind")
                        .HasFilter("trigger_type = 'full_scan' AND status IN ('queued', 'discovering', 'running')");

                    b.HasIndex("GameVersion", "Kind", "NormalizedRequestedSourceKey")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_import_runs_active_single_source")
                        .HasFilter("trigger_type = 'single_file' AND status IN ('queued', 'discovering', 'running')");

                    b.HasIndex("GameVersion", "Kind", "RequestedAt")
                        .HasDatabaseName("ix_asset_import_runs_kind_requested");

                    b.ToTable("asset_import_runs", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetImportWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<string>("ImportKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("import_kind");

                    b.Property<string>("NormalizedSourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_source_key");

                    b.Property<int>("ProcessedResourceCount")
                        .HasColumnType("integer")
                        .HasColumnName("processed_resource_count");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("SkippedResourceCount")
                        .HasColumnType("integer")
                        .HasColumnName("skipped_resource_count");

                    b.Property<string>("SourceHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_hash");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_key");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("source_path");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("TotalResourceCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_resource_count");

                    b.Property<DateTimeOffset?>("UnpublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unpublished_at");

                    b.Property<int>("WarningCount")
                        .HasColumnType("integer")
                        .HasColumnName("warning_count");

                    b.HasKey("Id");

                    b.HasIndex("GameVersion");

                    b.HasIndex("RunId", "NormalizedSourceKey")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_import_work_items_run_source");

                    b.HasIndex("RunId", "Status")
                        .HasDatabaseName("ix_asset_import_work_items_run_status");

                    b.ToTable("asset_import_work_items", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.GameVersion", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("SourceFolder")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_folder");

                    b.HasKey("Key");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("game_versions", "content");

                    b.HasData(
                        new
                        {
                            Key = "c1",
                            DisplayName = "Chronicle 1",
                            SortOrder = 10,
                            SourceFolder = "C1"
                        },
                        new
                        {
                            Key = "c4",
                            DisplayName = "Chronicle 4",
                            SortOrder = 20,
                            SourceFolder = "C4"
                        },
                        new
                        {
                            Key = "interlude",
                            DisplayName = "Interlude",
                            SortOrder = 30,
                            SourceFolder = "Interlude"
                        });
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.Npc", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("NpcRaceId")
                        .HasColumnType("integer")
                        .HasColumnName("npc_race_id");

                    b.Property<int>("NpcSexId")
                        .HasColumnType("integer")
                        .HasColumnName("npc_sex_id");

                    b.Property<int>("NpcTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("npc_type_id");

                    b.HasKey("GameVersion", "Id");

                    b.HasIndex("NpcRaceId")
                        .HasDatabaseName("ix_npcs_npc_race_id");

                    b.HasIndex("NpcSexId")
                        .HasDatabaseName("ix_npcs_npc_sex_id");

                    b.HasIndex("NpcTypeId")
                        .HasDatabaseName("ix_npcs_npc_type_id");

                    b.HasIndex("GameVersion", "NpcRaceId");

                    b.HasIndex("GameVersion", "NpcSexId");

                    b.HasIndex("GameVersion", "NpcTypeId");

                    b.ToTable("npcs", "content", t =>
                        {
                            t.HasCheckConstraint("ck_npcs_level", "level BETWEEN 1 AND 255");
                        });
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcRace", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id");

                    b.HasIndex("GameVersion", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_npc_races_name");

                    b.ToTable("npc_races", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcSex", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id");

                    b.HasIndex("GameVersion", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_npc_sexes_name");

                    b.ToTable("npc_sexes", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcType", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id");

                    b.HasIndex("GameVersion", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_npc_types_name");

                    b.ToTable("npc_types", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerClass", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("PlayerSexId")
                        .HasColumnType("integer")
                        .HasColumnName("player_sex_id");

                    b.Property<int>("PlayerRaceId")
                        .HasColumnType("integer")
                        .HasColumnName("player_race_id");

                    b.Property<bool>("IsMage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentClassId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_class_id");

                    b.HasKey("GameVersion", "Id", "PlayerSexId", "PlayerRaceId");

                    b.HasIndex("PlayerRaceId")
                        .HasDatabaseName("ix_player_classes_player_race_id");

                    b.HasIndex("PlayerSexId")
                        .HasDatabaseName("ix_player_classes_player_sex_id");

                    b.HasIndex("GameVersion", "PlayerRaceId");

                    b.HasIndex("GameVersion", "PlayerSexId");

                    b.HasIndex("ParentClassId", "PlayerSexId", "PlayerRaceId")
                        .HasDatabaseName("ix_player_classes_parent_sex_race");

                    b.HasIndex("GameVersion", "Name", "PlayerSexId", "PlayerRaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_classes_name_sex_race");

                    b.HasIndex("GameVersion", "ParentClassId", "PlayerSexId", "PlayerRaceId");

                    b.ToTable("player_classes", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerFace", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("PlayerSexId")
                        .HasColumnType("integer")
                        .HasColumnName("player_sex_id");

                    b.Property<int>("PlayerRaceId")
                        .HasColumnType("integer")
                        .HasColumnName("player_race_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id", "PlayerSexId", "PlayerRaceId");

                    b.HasIndex("GameVersion", "PlayerRaceId");

                    b.HasIndex("GameVersion", "PlayerSexId");

                    b.ToTable("player_faces", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerHairColor", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("PlayerSexId")
                        .HasColumnType("integer")
                        .HasColumnName("player_sex_id");

                    b.Property<int>("PlayerRaceId")
                        .HasColumnType("integer")
                        .HasColumnName("player_race_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id", "PlayerSexId", "PlayerRaceId");

                    b.HasIndex("GameVersion", "PlayerRaceId");

                    b.HasIndex("GameVersion", "PlayerSexId");

                    b.ToTable("player_hair_colors", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerHairStyle", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("PlayerSexId")
                        .HasColumnType("integer")
                        .HasColumnName("player_sex_id");

                    b.Property<int>("PlayerRaceId")
                        .HasColumnType("integer")
                        .HasColumnName("player_race_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id", "PlayerSexId", "PlayerRaceId");

                    b.HasIndex("GameVersion", "PlayerRaceId");

                    b.HasIndex("GameVersion", "PlayerSexId");

                    b.ToTable("player_hair_styles", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerRace", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id");

                    b.HasIndex("GameVersion", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_player_races_name");

                    b.ToTable("player_races", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerSex", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id");

                    b.HasIndex("GameVersion", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_player_sexes_name");

                    b.ToTable("player_sexes", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.Skill", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<short>("Levels")
                        .HasColumnType("smallint")
                        .HasColumnName("levels");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("SkillOperateTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_operate_type_id");

                    b.Property<int?>("SkillTargetTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_target_type_id");

                    b.HasKey("GameVersion", "Id");

                    b.HasIndex("SkillOperateTypeId")
                        .HasDatabaseName("ix_skills_skill_operate_type_id");

                    b.HasIndex("SkillTargetTypeId")
                        .HasDatabaseName("ix_skills_skill_target_type_id");

                    b.HasIndex("GameVersion", "SkillOperateTypeId");

                    b.HasIndex("GameVersion", "SkillTargetTypeId");

                    b.ToTable("skills", "content", t =>
                        {
                            t.HasCheckConstraint("ck_skills_levels", "levels BETWEEN 1 AND 255");
                        });
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.SkillIcon", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "SkillId", "Level");

                    b.ToTable("skill_icons", "content", t =>
                        {
                            t.HasCheckConstraint("ck_skill_icons_level", "level BETWEEN 1 AND 255");
                        });
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.SkillOperateType", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id");

                    b.HasIndex("GameVersion", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skill_operate_types_name");

                    b.ToTable("skill_operate_types", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.SkillTargetType", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id");

                    b.HasIndex("GameVersion", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skill_target_types_name");

                    b.ToTable("skill_target_types", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalog", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalogGroup", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.AssetCatalog", "Catalog")
                        .WithMany("Groups")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.AssetCatalogSource", "Source")
                        .WithMany("Groups")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalogItem", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.AssetCatalog", "Catalog")
                        .WithMany("Items")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.AssetCatalogSource", "Source")
                        .WithMany("Items")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalogSource", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.AssetCatalog", "Catalog")
                        .WithMany("Sources")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetImportDiagnostic", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.AssetImportRun", "Run")
                        .WithMany("Diagnostics")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.AssetImportWorkItem", "WorkItem")
                        .WithMany("Diagnostics")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Run");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetImportRun", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetImportWorkItem", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.AssetImportRun", "Run")
                        .WithMany("WorkItems")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.Npc", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.NpcRace", "NpcRace")
                        .WithMany("Npcs")
                        .HasForeignKey("GameVersion", "NpcRaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("L2.Studio.Context.Entities.NpcSex", "NpcSex")
                        .WithMany("Npcs")
                        .HasForeignKey("GameVersion", "NpcSexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.NpcType", "NpcType")
                        .WithMany("Npcs")
                        .HasForeignKey("GameVersion", "NpcTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NpcRace");

                    b.Navigation("NpcSex");

                    b.Navigation("NpcType");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcRace", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcSex", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcType", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerClass", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerRace", "PlayerRace")
                        .WithMany("PlayerClasses")
                        .HasForeignKey("GameVersion", "PlayerRaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerSex", "PlayerSex")
                        .WithMany("PlayerClasses")
                        .HasForeignKey("GameVersion", "PlayerSexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerClass", "ParentClass")
                        .WithMany("ChildClasses")
                        .HasForeignKey("GameVersion", "ParentClassId", "PlayerSexId", "PlayerRaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentClass");

                    b.Navigation("PlayerRace");

                    b.Navigation("PlayerSex");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerFace", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerRace", "PlayerRace")
                        .WithMany("PlayerFaces")
                        .HasForeignKey("GameVersion", "PlayerRaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerSex", "PlayerSex")
                        .WithMany("PlayerFaces")
                        .HasForeignKey("GameVersion", "PlayerSexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerRace");

                    b.Navigation("PlayerSex");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerHairColor", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerRace", "PlayerRace")
                        .WithMany("PlayerHairColors")
                        .HasForeignKey("GameVersion", "PlayerRaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerSex", "PlayerSex")
                        .WithMany("PlayerHairColors")
                        .HasForeignKey("GameVersion", "PlayerSexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerRace");

                    b.Navigation("PlayerSex");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerHairStyle", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerRace", "PlayerRace")
                        .WithMany("PlayerHairStyles")
                        .HasForeignKey("GameVersion", "PlayerRaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerSex", "PlayerSex")
                        .WithMany("PlayerHairStyles")
                        .HasForeignKey("GameVersion", "PlayerSexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerRace");

                    b.Navigation("PlayerSex");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerRace", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerSex", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.Skill", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.SkillOperateType", "SkillOperateType")
                        .WithMany("Skills")
                        .HasForeignKey("GameVersion", "SkillOperateTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("L2.Studio.Context.Entities.SkillTargetType", "SkillTargetType")
                        .WithMany("Skills")
                        .HasForeignKey("GameVersion", "SkillTargetTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SkillOperateType");

                    b.Navigation("SkillTargetType");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.SkillIcon", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.Skill", "Skill")
                        .WithMany("SkillIcons")
                        .HasForeignKey("GameVersion", "SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.SkillOperateType", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.SkillTargetType", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalog", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Items");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalogSource", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetImportRun", b =>
                {
                    b.Navigation("Diagnostics");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetImportWorkItem", b =>
                {
                    b.Navigation("Diagnostics");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcRace", b =>
                {
                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcSex", b =>
                {
                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcType", b =>
                {
                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerClass", b =>
                {
                    b.Navigation("ChildClasses");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerRace", b =>
                {
                    b.Navigation("PlayerClasses");

                    b.Navigation("PlayerFaces");

                    b.Navigation("PlayerHairColors");

                    b.Navigation("PlayerHairStyles");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerSex", b =>
                {
                    b.Navigation("PlayerClasses");

                    b.Navigation("PlayerFaces");

                    b.Navigation("PlayerHairColors");

                    b.Navigation("PlayerHairStyles");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.Skill", b =>
                {
                    b.Navigation("SkillIcons");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.SkillOperateType", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.SkillTargetType", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
