// <auto-generated />
using System;
using L2.Studio.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace L2.Studio.Migrations.Migrations
{
    [DbContext(typeof(GameContentDbContext))]
    [Migration("20260812223137_NameKeyedNpcLookups")]
    partial class NameKeyedNpcLookups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuildFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("build_fingerprint");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer")
                        .HasColumnName("file_count");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_version");

                    b.Property<string>("IntegrityStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("integrity_status");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at");

                    b.Property<string>("NormalizedSourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_source_key");

                    b.Property<string>("OutputRoot")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("output_root");

                    b.Property<int?>("Protocol")
                        .HasColumnType("integer")
                        .HasColumnName("protocol");

                    b.Property<Guid>("PublishingWorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("publishing_work_item_id");

                    b.Property<string>("RecipeVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("recipe_version");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_hash");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_key");

                    b.HasKey("Id");

                    b.HasIndex("OutputRoot")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_artifacts_output_root");

                    b.HasIndex("PublishingWorkItemId");

                    b.HasIndex("GameVersion", "Kind", "IntegrityStatus")
                        .HasDatabaseName("ix_asset_artifacts_integrity");

                    b.HasIndex("GameVersion", "Kind", "NormalizedSourceKey", "BuildFingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_artifacts_build");

                    b.ToTable("asset_artifacts", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetArtifactDependency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<string>("BuildFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("build_fingerprint");

                    b.Property<string>("DependencyKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("dependency_key");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("ResolvedArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_artifact_id");

                    b.Property<string>("ResolvedSourceKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("resolved_source_key");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedArtifactId")
                        .HasDatabaseName("ix_asset_artifact_dependencies_resolved");

                    b.HasIndex("ArtifactId", "Kind", "DependencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_artifact_dependencies_key");

                    b.ToTable("asset_artifact_dependencies", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetArtifactFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("media_type");

                    b.Property<string>("PublicPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("public_path");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("relative_path");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId", "RelativePath")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_artifact_files_path");

                    b.ToTable("asset_artifact_files", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<int?>("Protocol")
                        .HasColumnType("integer")
                        .HasColumnName("protocol");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("SourceFolder")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_folder");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_hash");

                    b.HasKey("Id");

                    b.HasIndex("GameVersion", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_catalogs_active_kind")
                        .HasFilter("is_active");

                    b.ToTable("asset_catalogs", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalogGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("CatalogId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_catalog_groups_catalog_name");

                    b.ToTable("asset_catalog_groups", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalogItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<string>("GroupName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("group_name");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("CatalogId", "Name")
                        .HasDatabaseName("ix_asset_catalog_items_catalog_name");

                    b.HasIndex("CatalogId", "Status")
                        .HasDatabaseName("ix_asset_catalog_items_catalog_status");

                    b.HasIndex("CatalogId", "GroupName", "Name")
                        .HasDatabaseName("ix_asset_catalog_items_catalog_group_name");

                    b.ToTable("asset_catalog_items", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalogSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("artifact_fingerprint");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<Guid>("CatalogId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_id");

                    b.Property<bool>("IsStale")
                        .HasColumnType("boolean")
                        .HasColumnName("is_stale");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<string>("NormalizedSourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_source_key");

                    b.Property<string>("OutputRoot")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("output_root");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("PublishingWorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("publishing_work_item_id");

                    b.Property<string>("ReferencedOutputRootsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("referenced_output_roots_json");

                    b.Property<string>("SourceHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_hash");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_key");

                    b.Property<DateTimeOffset?>("StaleAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stale_at");

                    b.Property<string>("StaleReasonsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("stale_reasons_json")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("CatalogId", "NormalizedSourceKey")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_catalog_sources_catalog_source");

                    b.ToTable("asset_catalog_sources", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalogSourceDependency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ArtifactFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("artifact_fingerprint");

                    b.Property<string>("DependencyKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("dependency_key");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_resolved");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("ResolvedSourceKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("resolved_source_key");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("Kind", "DependencyKey")
                        .HasDatabaseName("ix_asset_catalog_source_dependencies_key");

                    b.HasIndex("Kind", "ResolvedSourceKey")
                        .HasDatabaseName("ix_asset_catalog_source_dependencies_source");

                    b.ToTable("asset_catalog_source_dependencies", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetImportDiagnostic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message");

                    b.Property<string>("ObjectName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_name");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_key");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stage");

                    b.Property<Guid?>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey")
                        .HasDatabaseName("ix_asset_import_diagnostics_source_key");

                    b.HasIndex("WorkItemId");

                    b.HasIndex("RunId", "Severity", "Code", "Stage")
                        .HasDatabaseName("ix_asset_import_diagnostics_filters");

                    b.ToTable("asset_import_diagnostics", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CompletedFileCount")
                        .HasColumnType("integer")
                        .HasColumnName("completed_file_count");

                    b.Property<int>("DiscoveredFileCount")
                        .HasColumnType("integer")
                        .HasColumnName("discovered_file_count");

                    b.Property<DateTimeOffset?>("DiscoveryFinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovery_finished_at");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<int>("FailedFileCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_file_count");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<bool>("Force")
                        .HasColumnType("boolean")
                        .HasColumnName("force");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<string>("NormalizedRequestedSourceKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_requested_source_key");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequestedSourceKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("requested_source_key");

                    b.Property<int>("ReusedFileCount")
                        .HasColumnType("integer")
                        .HasColumnName("reused_file_count");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("SucceededFileCount")
                        .HasColumnType("integer")
                        .HasColumnName("succeeded_file_count");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trigger_type");

                    b.Property<int>("WarningFileCount")
                        .HasColumnType("integer")
                        .HasColumnName("warning_file_count");

                    b.HasKey("Id");

                    b.HasIndex("GameVersion", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_import_runs_active_full_scan_kind")
                        .HasFilter("trigger_type = 'full_scan' AND status IN ('queued', 'discovering', 'running')");

                    b.HasIndex("GameVersion", "Kind", "NormalizedRequestedSourceKey")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_import_runs_active_single_source")
                        .HasFilter("trigger_type = 'single_file' AND status IN ('queued', 'discovering', 'running')");

                    b.HasIndex("GameVersion", "Kind", "RequestedAt")
                        .HasDatabaseName("ix_asset_import_runs_kind_requested");

                    b.ToTable("asset_import_runs", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetImportWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("artifact_fingerprint");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<string>("ImportKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("import_kind");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<string>("NormalizedSourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_source_key");

                    b.Property<int>("ProcessedResourceCount")
                        .HasColumnType("integer")
                        .HasColumnName("processed_resource_count");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("SkippedResourceCount")
                        .HasColumnType("integer")
                        .HasColumnName("skipped_resource_count");

                    b.Property<string>("SourceHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_hash");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_key");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("source_path");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("TotalResourceCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_resource_count");

                    b.Property<DateTimeOffset?>("UnpublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unpublished_at");

                    b.Property<int>("WarningCount")
                        .HasColumnType("integer")
                        .HasColumnName("warning_count");

                    b.HasKey("Id");

                    b.HasIndex("GameVersion");

                    b.HasIndex("RunId", "NormalizedSourceKey")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_import_work_items_run_source");

                    b.HasIndex("RunId", "Status")
                        .HasDatabaseName("ix_asset_import_work_items_run_status");

                    b.ToTable("asset_import_work_items", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CharacterSelectionCameraSequence")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("character_selection_camera_sequence");

                    b.Property<long?>("CharacterSelectionSceneFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("character_selection_scene_file_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_version");

                    b.Property<long?>("LoadingArtworkFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("loading_artwork_file_id");

                    b.Property<string>("LoginCameraSequence")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("login_camera_sequence");

                    b.Property<long?>("LoginMusicFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("login_music_file_id");

                    b.Property<long?>("LoginSceneFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("login_scene_file_id");

                    b.Property<string>("ManifestHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("manifest_hash");

                    b.Property<string>("ManifestPath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("manifest_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("notes");

                    b.Property<long?>("PrimaryLogoFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("primary_logo_file_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_at");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("snapshot_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.Property<string>("ValidatedSnapshotHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("validated_snapshot_hash");

                    b.Property<string>("ValidationIssuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_issues_json");

                    b.Property<DateTimeOffset?>("ValidationRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validation_requested_at");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("validation_status");

                    b.Property<long?>("VersionLogoFileId")
                        .HasColumnType("bigint")
                        .HasColumnName("version_logo_file_id");

                    b.HasKey("Id");

                    b.HasIndex("CharacterSelectionSceneFileId");

                    b.HasIndex("LoadingArtworkFileId");

                    b.HasIndex("LoginMusicFileId");

                    b.HasIndex("LoginSceneFileId");

                    b.HasIndex("PrimaryLogoFileId");

                    b.HasIndex("VersionLogoFileId");

                    b.HasIndex("GameVersion", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_releases_version_name");

                    b.HasIndex("GameVersion", "Status", "CreatedAt")
                        .HasDatabaseName("ix_asset_releases_version_status");

                    b.ToTable("asset_releases", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetReleaseArtifact", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<bool>("IsRoot")
                        .HasColumnType("boolean")
                        .HasColumnName("is_root");

                    b.HasKey("ReleaseId", "ArtifactId");

                    b.HasIndex("ArtifactId")
                        .HasDatabaseName("ix_asset_release_artifacts_artifact");

                    b.ToTable("asset_release_artifacts", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetReleaseEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.ToTable("asset_release_events", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetReleasePointer", b =>
                {
                    b.Property<string>("GameVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("game_version");

                    b.Property<Guid?>("DesiredReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("desired_release_id");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("PublishedReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("published_release_id");

                    b.Property<DateTimeOffset?>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("GameVersion");

                    b.HasIndex("DesiredReleaseId");

                    b.HasIndex("PublishedReleaseId");

                    b.ToTable("asset_release_pointers", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.GameVersion", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("key");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("SourceFolder")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_folder");

                    b.HasKey("Key");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("game_versions", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.Npc", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NpcRaceName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("npc_race_name");

                    b.Property<string>("NpcSexName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("npc_sex_name");

                    b.Property<string>("NpcTypeName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("npc_type_name");

                    b.HasKey("GameVersion", "Id");

                    b.HasIndex("GameVersion", "NpcRaceName")
                        .HasDatabaseName("ix_npcs_npc_race_name");

                    b.HasIndex("GameVersion", "NpcSexName")
                        .HasDatabaseName("ix_npcs_npc_sex_name");

                    b.HasIndex("GameVersion", "NpcTypeName")
                        .HasDatabaseName("ix_npcs_npc_type_name");

                    b.ToTable("npcs", "content", t =>
                        {
                            t.HasCheckConstraint("ck_npcs_level", "level BETWEEN 1 AND 255");
                        });
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcLookupImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<int>("ExistingCount")
                        .HasColumnType("integer")
                        .HasColumnName("existing_count");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("GameVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("InsertedCount")
                        .HasColumnType("integer")
                        .HasColumnName("inserted_count");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_count");

                    b.HasKey("Id");

                    b.HasIndex("GameVersion", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_npc_lookup_import_runs_active")
                        .HasFilter("status IN ('queued', 'running')");

                    b.HasIndex("GameVersion", "Kind", "RequestedAt")
                        .HasDatabaseName("ix_npc_lookup_import_runs_recent");

                    b.ToTable("npc_lookup_import_runs", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcRace", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.HasKey("GameVersion", "Name");

                    b.ToTable("npc_races", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcSex", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.HasKey("GameVersion", "Name");

                    b.ToTable("npc_sexes", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcType", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<string>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.HasKey("GameVersion", "Name");

                    b.ToTable("npc_types", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerClass", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("PlayerSexId")
                        .HasColumnType("integer")
                        .HasColumnName("player_sex_id");

                    b.Property<int>("PlayerRaceId")
                        .HasColumnType("integer")
                        .HasColumnName("player_race_id");

                    b.Property<bool>("IsMage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_mage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentClassId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_class_id");

                    b.HasKey("GameVersion", "Id", "PlayerSexId", "PlayerRaceId");

                    b.HasIndex("PlayerRaceId")
                        .HasDatabaseName("ix_player_classes_player_race_id");

                    b.HasIndex("PlayerSexId")
                        .HasDatabaseName("ix_player_classes_player_sex_id");

                    b.HasIndex("GameVersion", "PlayerRaceId");

                    b.HasIndex("GameVersion", "PlayerSexId");

                    b.HasIndex("ParentClassId", "PlayerSexId", "PlayerRaceId")
                        .HasDatabaseName("ix_player_classes_parent_sex_race");

                    b.HasIndex("GameVersion", "Name", "PlayerSexId", "PlayerRaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_classes_name_sex_race");

                    b.HasIndex("GameVersion", "ParentClassId", "PlayerSexId", "PlayerRaceId");

                    b.ToTable("player_classes", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerFace", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("PlayerSexId")
                        .HasColumnType("integer")
                        .HasColumnName("player_sex_id");

                    b.Property<int>("PlayerRaceId")
                        .HasColumnType("integer")
                        .HasColumnName("player_race_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id", "PlayerSexId", "PlayerRaceId");

                    b.HasIndex("GameVersion", "PlayerRaceId");

                    b.HasIndex("GameVersion", "PlayerSexId");

                    b.ToTable("player_faces", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerHairColor", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("PlayerSexId")
                        .HasColumnType("integer")
                        .HasColumnName("player_sex_id");

                    b.Property<int>("PlayerRaceId")
                        .HasColumnType("integer")
                        .HasColumnName("player_race_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id", "PlayerSexId", "PlayerRaceId");

                    b.HasIndex("GameVersion", "PlayerRaceId");

                    b.HasIndex("GameVersion", "PlayerSexId");

                    b.ToTable("player_hair_colors", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerHairStyle", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("PlayerSexId")
                        .HasColumnType("integer")
                        .HasColumnName("player_sex_id");

                    b.Property<int>("PlayerRaceId")
                        .HasColumnType("integer")
                        .HasColumnName("player_race_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id", "PlayerSexId", "PlayerRaceId");

                    b.HasIndex("GameVersion", "PlayerRaceId");

                    b.HasIndex("GameVersion", "PlayerSexId");

                    b.ToTable("player_hair_styles", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerRace", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id");

                    b.HasIndex("GameVersion", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_player_races_name");

                    b.ToTable("player_races", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerSex", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id");

                    b.HasIndex("GameVersion", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_player_sexes_name");

                    b.ToTable("player_sexes", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.Skill", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<short>("Levels")
                        .HasColumnType("smallint")
                        .HasColumnName("levels");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("SkillOperateTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_operate_type_id");

                    b.Property<int?>("SkillTargetTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_target_type_id");

                    b.HasKey("GameVersion", "Id");

                    b.HasIndex("SkillOperateTypeId")
                        .HasDatabaseName("ix_skills_skill_operate_type_id");

                    b.HasIndex("SkillTargetTypeId")
                        .HasDatabaseName("ix_skills_skill_target_type_id");

                    b.HasIndex("GameVersion", "SkillOperateTypeId");

                    b.HasIndex("GameVersion", "SkillTargetTypeId");

                    b.ToTable("skills", "content", t =>
                        {
                            t.HasCheckConstraint("ck_skills_levels", "levels BETWEEN 1 AND 255");
                        });
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.SkillIcon", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.Property<short>("Level")
                        .HasColumnType("smallint")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "SkillId", "Level");

                    b.ToTable("skill_icons", "content", t =>
                        {
                            t.HasCheckConstraint("ck_skill_icons_level", "level BETWEEN 1 AND 255");
                        });
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.SkillOperateType", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id");

                    b.HasIndex("GameVersion", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skill_operate_types_name");

                    b.ToTable("skill_operate_types", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.SkillTargetType", b =>
                {
                    b.Property<string>("GameVersion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("interlude")
                        .HasColumnName("game_version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("GameVersion", "Id");

                    b.HasIndex("GameVersion", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skill_target_types_name");

                    b.ToTable("skill_target_types", "content");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetArtifact", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.AssetImportWorkItem", "PublishingWorkItem")
                        .WithMany()
                        .HasForeignKey("PublishingWorkItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PublishingWorkItem");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetArtifactDependency", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.AssetArtifact", "Artifact")
                        .WithMany("Dependencies")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.AssetArtifact", "ResolvedArtifact")
                        .WithMany()
                        .HasForeignKey("ResolvedArtifactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Artifact");

                    b.Navigation("ResolvedArtifact");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetArtifactFile", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.AssetArtifact", "Artifact")
                        .WithMany("Files")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalog", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalogGroup", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.AssetCatalog", "Catalog")
                        .WithMany("Groups")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.AssetCatalogSource", "Source")
                        .WithMany("Groups")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalogItem", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.AssetCatalog", "Catalog")
                        .WithMany("Items")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.AssetCatalogSource", "Source")
                        .WithMany("Items")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalogSource", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.AssetArtifact", "Artifact")
                        .WithMany("Publications")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.AssetCatalog", "Catalog")
                        .WithMany("Sources")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalogSourceDependency", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.AssetCatalogSource", "Source")
                        .WithMany("Dependencies")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetImportDiagnostic", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.AssetImportRun", "Run")
                        .WithMany("Diagnostics")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.AssetImportWorkItem", "WorkItem")
                        .WithMany("Diagnostics")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Run");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetImportRun", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetImportWorkItem", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.AssetImportRun", "Run")
                        .WithMany("WorkItems")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetRelease", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.AssetArtifactFile", null)
                        .WithMany()
                        .HasForeignKey("CharacterSelectionSceneFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.AssetArtifactFile", null)
                        .WithMany()
                        .HasForeignKey("LoadingArtworkFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("L2.Studio.Context.Entities.AssetArtifactFile", null)
                        .WithMany()
                        .HasForeignKey("LoginMusicFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("L2.Studio.Context.Entities.AssetArtifactFile", null)
                        .WithMany()
                        .HasForeignKey("LoginSceneFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("L2.Studio.Context.Entities.AssetArtifactFile", null)
                        .WithMany()
                        .HasForeignKey("PrimaryLogoFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("L2.Studio.Context.Entities.AssetArtifactFile", null)
                        .WithMany()
                        .HasForeignKey("VersionLogoFileId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetReleaseArtifact", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.AssetArtifact", "Artifact")
                        .WithMany("Releases")
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.AssetRelease", "Release")
                        .WithMany("Artifacts")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetReleaseEvent", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.AssetRelease", "Release")
                        .WithMany("Events")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetReleasePointer", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.AssetRelease", "DesiredRelease")
                        .WithMany()
                        .HasForeignKey("DesiredReleaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithOne()
                        .HasForeignKey("L2.Studio.Context.Entities.AssetReleasePointer", "GameVersion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.AssetRelease", "PublishedRelease")
                        .WithMany()
                        .HasForeignKey("PublishedReleaseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DesiredRelease");

                    b.Navigation("PublishedRelease");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.Npc", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.NpcRace", "NpcRace")
                        .WithMany("Npcs")
                        .HasForeignKey("GameVersion", "NpcRaceName")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("L2.Studio.Context.Entities.NpcSex", "NpcSex")
                        .WithMany("Npcs")
                        .HasForeignKey("GameVersion", "NpcSexName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.NpcType", "NpcType")
                        .WithMany("Npcs")
                        .HasForeignKey("GameVersion", "NpcTypeName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NpcRace");

                    b.Navigation("NpcSex");

                    b.Navigation("NpcType");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcLookupImportRun", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcRace", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcSex", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcType", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerClass", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerRace", "PlayerRace")
                        .WithMany("PlayerClasses")
                        .HasForeignKey("GameVersion", "PlayerRaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerSex", "PlayerSex")
                        .WithMany("PlayerClasses")
                        .HasForeignKey("GameVersion", "PlayerSexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerClass", "ParentClass")
                        .WithMany("ChildClasses")
                        .HasForeignKey("GameVersion", "ParentClassId", "PlayerSexId", "PlayerRaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentClass");

                    b.Navigation("PlayerRace");

                    b.Navigation("PlayerSex");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerFace", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerRace", "PlayerRace")
                        .WithMany("PlayerFaces")
                        .HasForeignKey("GameVersion", "PlayerRaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerSex", "PlayerSex")
                        .WithMany("PlayerFaces")
                        .HasForeignKey("GameVersion", "PlayerSexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerRace");

                    b.Navigation("PlayerSex");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerHairColor", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerRace", "PlayerRace")
                        .WithMany("PlayerHairColors")
                        .HasForeignKey("GameVersion", "PlayerRaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerSex", "PlayerSex")
                        .WithMany("PlayerHairColors")
                        .HasForeignKey("GameVersion", "PlayerSexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerRace");

                    b.Navigation("PlayerSex");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerHairStyle", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerRace", "PlayerRace")
                        .WithMany("PlayerHairStyles")
                        .HasForeignKey("GameVersion", "PlayerRaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.PlayerSex", "PlayerSex")
                        .WithMany("PlayerHairStyles")
                        .HasForeignKey("GameVersion", "PlayerSexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerRace");

                    b.Navigation("PlayerSex");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerRace", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerSex", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.Skill", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.SkillOperateType", "SkillOperateType")
                        .WithMany("Skills")
                        .HasForeignKey("GameVersion", "SkillOperateTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("L2.Studio.Context.Entities.SkillTargetType", "SkillTargetType")
                        .WithMany("Skills")
                        .HasForeignKey("GameVersion", "SkillTargetTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SkillOperateType");

                    b.Navigation("SkillTargetType");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.SkillIcon", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("L2.Studio.Context.Entities.Skill", "Skill")
                        .WithMany("SkillIcons")
                        .HasForeignKey("GameVersion", "SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.SkillOperateType", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.SkillTargetType", b =>
                {
                    b.HasOne("L2.Studio.Context.Entities.GameVersion", null)
                        .WithMany()
                        .HasForeignKey("GameVersion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetArtifact", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Files");

                    b.Navigation("Publications");

                    b.Navigation("Releases");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalog", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Items");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetCatalogSource", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Groups");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetImportRun", b =>
                {
                    b.Navigation("Diagnostics");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetImportWorkItem", b =>
                {
                    b.Navigation("Diagnostics");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.AssetRelease", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcRace", b =>
                {
                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcSex", b =>
                {
                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.NpcType", b =>
                {
                    b.Navigation("Npcs");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerClass", b =>
                {
                    b.Navigation("ChildClasses");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerRace", b =>
                {
                    b.Navigation("PlayerClasses");

                    b.Navigation("PlayerFaces");

                    b.Navigation("PlayerHairColors");

                    b.Navigation("PlayerHairStyles");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.PlayerSex", b =>
                {
                    b.Navigation("PlayerClasses");

                    b.Navigation("PlayerFaces");

                    b.Navigation("PlayerHairColors");

                    b.Navigation("PlayerHairStyles");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.Skill", b =>
                {
                    b.Navigation("SkillIcons");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.SkillOperateType", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("L2.Studio.Context.Entities.SkillTargetType", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
