<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><IsPackable>false</IsPackable><IsTestProject>true</IsTestProject></PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio"><PrivateAssets>all</PrivateAssets><IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets></PackageReference>
    <ProjectReference Include="../../src/L2.Studio.Configurations/L2.Studio.Configurations.csproj" />
    <ProjectReference Include="../../src/L2.Studio.Repositories.Interfaces/L2.Studio.Repositories.Interfaces.csproj" />
    <ProjectReference Include="../../src/L2.Studio.Services.Interfaces/L2.Studio.Services.Interfaces.csproj" />
  </ItemGroup>
</Project>
